Django_f/Django_f/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bug/', include('apps.result.urls')),
    path('api/', include('apps.apitest.urls')),
    path('db/', include('apps.db.urls')),
    path('appcase/', include('apps.apptest.urls')),
    path('webcase/', include('apps.webtest.urls')),
    path('message/', include('apps.message.urls')),
    path('admin/', admin.site.urls),
]

Django_f/apps/apptest/urls.py
from django.urls import path
from apps.apptest import views

app_name = 'apptest'
urlpatterns = [
    path('appcase_manage/', views.appcase_manage, name='case'),
    path('appcasestep_manage/', views.appcasestep_manage, name='step'),
    path('appsearch/', views.appsearch, name='case'),
    path('appstepsearch/', views.appstepsearch, name='step'),

]

Django_f/apps/apptest/models.py
from django.db import models

# Create your models here.
class Appcase(models.Model):
 Product = models.ForeignKey('message.Product',on_delete=models.CASCADE,null=True)
# 关联产品 ID
 appcasename = models.CharField('用例名称',max_length=200) # 测试用例名称
 apptestresult = models.BooleanField('测试结果') # 测试结果
 apptester = models.CharField('测试负责人',max_length=16) # 执行人
 create_time = models.DateTimeField('创建时间',auto_now=True) # 创建时间，自动获# 取当前时间
 class Meta:
  verbose_name = 'app 测试用例'
  verbose_name_plural = 'app 测试用例'
 def __str__(self):
  return self.appcasename
class Appcasestep(models.Model):
 Appcase = models.ForeignKey(Appcase,on_delete=models.CASCADE) # 关联接口 ID
 appteststep = models.CharField('测试步骤',max_length=200) # 测试步骤
 apptestobjname = models.CharField('测试对象名称描述',max_length=200) # 测试对象名# 称描述
 appfindmethod = models.CharField('定位方式',max_length=200) # 定位方式
 appevelement = models.CharField('控件元素',max_length=800) # 控件元素
 appoptmethod = models.CharField('操作方法',max_length=200) # 操作方法
 apptestdata = models.CharField('测试数据',max_length=200,null=True) # 测试
# 数据，临时增加字段时要设置可为空
 appassertdata = models.CharField('验证数据',max_length=200) # 验证数据
 apptestresult = models.BooleanField('测试结果') # 测试结果
 create_time = models.DateTimeField('创建时间',auto_now=True) # 创建时间，自动# 获取当前时间
 def __str__(self):
  return self.appteststep

Django_f/apps/apptest/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from apps.apptest.models import Appcase, Appcasestep
# Create your views here.
# app 用例管理
# @login_required
def appcase_manage(request):
 appcase_list = Appcase.objects.all().order_by('id')
 username = request.session['username'] # 读取浏览器登录 Session
 paginator = Paginator(appcase_list, 1)  # 生成 paginator 对象,设置每页显示 8 条记录
 page = request.GET.get('page', 1)  # 获取当前的页码数,默认为第 1 页
 currentPage = int(page)  # 把获取的当前页码数转换成整数类型
 try:
  appcase_list = paginator.page(page)  # 获取当前页码数的记录列表
 except PageNotAnInteger:
  appcase_list = paginator.page(1)  # 如果输入的页数不是整数则显示第 1 页的内容
 except EmptyPage:
  appcase_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数# 中则显示最后一页的内容
 appcase_count = Appcase.objects.all().count()  # 统计产品数
 return render(request, "apptest/testcase.html", {"user": username,"appcases":
  appcase_list, "appcasecounts": appcase_count})  # 把值赋给 appcasecounts 变量
# App 用例测试步骤
# @login_required
def appcasestep_manage(request):
 username = request.session['username']
 appcasestep_list = Appcasestep.objects.all().order_by('id')
 paginator = Paginator(appcasestep_list, 1)  # 生成 paginator 对象,设置每页显示 8 条记# 录
 page = request.GET.get('page', 1)  # 获取当前的页码数,默认为第 1 页
 currentPage = int(page)  # 把获取的当前页码数转换成整数类型
 try:
  appcasestep_list = paginator.page(page)  # 获取当前页码数的记录列表
 except PageNotAnInteger:
  appcasestep_list = paginator.page(1)  # 如果输入的页数不是整数则显示第 1 页的内容
 except EmptyPage:
  appcasestep_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统
 # 的页数中则显示最后一页
 return render(request, "apptest/testsep.html", {"user": username,"appcasesteps":
appcasestep_list})

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# 搜索功能
# @login_required
def appsearch(request):
 username = request.session['username'] # 读取浏览器登录 Session
 search_appcasename = request.GET.get("appcasename", "")
 appcase_list = Appcase.objects.filter(appcasename__icontains=search_appcasename)
 return render(request,'apptest/testcase.html', {"user": username,"appcases":appcase_list})
# 搜索功能
# @login_required
def appstepsearch(request):
 print(Appcasestep.objects.all())
 username = request.session['username']# 读取浏览器登录 Session
 search_appcasename = request.GET.get("appcasename", "")
 appcasestep_list = Appcasestep.objects.filter(apptestobjname__icontains=search_appcasename)
 return render(request,'apptest/testsep.html', {"user":
username,"appcasesteps":appcasestep_list})

Django_f/templates/apptest/report.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试报告管理平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!-- 测试报告-->
<div class="row" style="padding-top: 55px;">
<div class="col-md-11">
<table class="table table-striped">
<div style="position:absolute; right:10px; width:10px; ">
<tr><th></th><th></th><th></th><th></th><th></th><th>单一接口扫描-自动化测试汇总报告</th></tr>
<tr><th>用例总数</th>
<td>{{ apiscounts }}</td><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th><
/th></tr> {# 前端读取定义的变量#}
<tr><th>通过
</th><td>{{ apis_pass_counts }}</td><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th
></th><th></th></tr>
<tr><th>不通过</th><td><a style='color:red'>{{ apis_fail_counts }}</a>
</td><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th></tr>
</div>
</table>
<!-- 单一接口测试用例-->
<table class="table table-striped">
<thead>
<tr><th>失败接口列表</th><td>
<tr>
<th>ID</th><th>产品</th><th>测试用例名称</th><th>URL 地址</th><th>参数=值</th><th>方法</th><th>预期</th><th>
测试结果</th><th>执行时间</th>
</tr>
</thead>
<tbody>
{% for apis in apiss %}
<tr>
{% if apis.apistatus == 0 %}
<td>{{apis.id}}</td>
<td>{{ apis.Product.productname }}</td>
<td>{{ apis.apiname }}</td>
<td>{{ apis.apiurl }}</td>
<td>{{ apis.apiparamvalue }}</td>
<td>{{ apis.apimethod }}</td>
<td>{{ apis.apiresult }}</td>
<td>{% if apis.apistatus == 1 %}
<a style='color:green'>{{ apis.apistatus }}</a>
{% else %}
<a style='color:red'>{{ apis.apistatus }}</a>
{% endif %}
</td>
<td>{{ apis.create_time }}</td>
{% else %}
{% endif %}
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</body>
</html>

Django_f/templates/apptest/testcase.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试管理平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
<li><a style='color:white' href="/appcase/appcase_manage/">app 测试用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase/appcasestep_manage/">app 测试用例步骤</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
<form class="navbar-form" method="get" action="/appcase/appsearch/">
{% csrf_token %}
<input type="search" name="appcasename" placeholder="名称" required>
<button type="submit">搜索</button>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximumscale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />
<!-- 增加 app 测试用例-->
<div style="float:right;width:73%">
<select name="Appcase" id="id_Appcase">
<option value="" selected>----app 测试用例----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Appcase" data-hreftemplate="/admin/apptest/appcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Appcase"
href="/admin/apptest/appcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</div>
</form>
</div>
<!-- app 测试用例列表-->
<div class="row" style="padding-top: 50px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
<tr>
<th>ID</th><th>产品</th><th>测试用例名称</th><th>测试结果</th><th>测试负责人</th><th>时间</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for appcase in appcases %}
<tr>
<td>{{ appcase.id }}</td>
<td>{{ appcase.Product.productname }}</td>
<td>{{ appcase.appcasename }}</td>
<td>{{ appcase.apptestresult }}</td>
<td>{{ appcase.apptester }}</td>
<td>{{ appcase.create_time }}</td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Appcase"
href="/admin/apptest/appcase/{{ appcase.id }}/change/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-changelink.svg"/></a></td>

<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Appcase"
href="/admin/apptest/appcase/{{ appcase.id }}/delete/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div class="container">
 <ul class="pagination" id="pager">
 {# 上一页链接开始#}
 {% if appcases.has_previous %}
 {# 如果有上一页，则正常显示上一页的链接#}
 <li class="previous"><a href="/appcase/appcase_manage/?page={{ appcases.previous_page_number }}">上
一页</a></li> {# 上一页标签 #}
 {% else %}
 <li class="previous disabled"><a href="#">上一页</a></li>
     {# 如果当前不存在上一页，则上一页的链接不可单击#}
 {% endif %}
 {# 上一页链接开始#}

 {% for num in appcases.paginator.page_range %}

 {% if num == currentPage %}
 <li class="item active"><a href="/appcase/appcase_manage/?page={{ num }}">{{ num }}</a></li>
{#显示当前页数链接#}
 {% else %}
 <li class="item"><a href="/appcase/appcase_manage/?page={{ num }}">{{ num }}</a></li>
 {% endif %}
 {% endfor %}

 {# 下一页链接开始#}
 {% if appcases.has_next %} {#如果有下一页，则正常显示下一页的链接#}
 <li class="next"><a href="/appcase/appcase_manage/?page={{ appcases.next_page_number }}">下一页
</a></li>
 {% else %}
 <li class="next disabled"><a href="#">下一页</a></li>
 {% endif %}
 {# 下一页链接结束#}
 </ul>
</div>
</span>
<!--统计和翻页功能-->
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:100px; width:100px; ">
<tr><th>总数</th><td>{{ appcasecounts }}</td></tr> {# 前端读取定义的变量#}
</div>
</span>
</body>
</html>

Django_f/templates/apptest/testsep.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
<li><a style='color:white' href="/appcase/appcase_manage/">app 测试用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase/appcasestep_manage/">app 测试用例步骤</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
<form class="navbar-form" method="get" action="/appcase/appstepsearch/">
{% csrf_token %}
<input type="search" name="appcasename" placeholder="名称" required>
<button type="submit">搜索</button>
</form>
</div>
<!-- 流程测试步骤-->
<div class="row" style="padding-top: 50px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
<tr>
<th>所属产品</th><th>所属用例</th><th>步骤</th><th>定位方式</th><th>控件元素</th><th>操作方法</th><th>测试数据
</th><th>验证数据</th><th>测试结果</th><th>时间</th>
</tr>
</thead>
<tbody>
{% for appcasestep in appcasesteps %}
<tr>
<td>{{ appcasestep.Appcase.Product.productname }}</td>
<td>case{{ appcasestep.Appcase.id }}:{{ appcasestep.Appcase.appcasename }}</td>
<td>{{ appcasestep.appteststep }}:{{ appcasestep.apptestobjname }}</td>
<td>{{ appcasestep.appfindmethod }}</td>
<td>{{ appcasestep.appevelement }}</td>
<td>{{ appcasestep.appoptmethod }}</td>
<td>{{ appcasestep.apptestdata }}</td>
<td>{{ appcasestep.appassertdata }}</td>
<td>{% if appcasestep.apptestresult == 1 %}
<a style='color:green'>{{ appcasestep.apptestresult }}</a>
{% else %}
<a style='color:red'>{{ appcasestep.apptestresult }}</a>
{% endif %}
</td>
<td>{{ appcasestep.create_time }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div class="container">
 <ul class="pagination" id="pager">
 {# 上一页链接开始#}
 {% if appcasesteps.has_previous %}
 {# 如果有上一页，则正常显示上一页的链接#}
 <li class="previous"><a
href="/appcase/appcasestep_manage/?page={{ appcasesteps.previous_page_number }}">上一页</a></li>
     {# 上一页标签 #}
 {% else %}
 <li class="previous disabled"><a href="#">上一页</a></li>
     {# 如果当前不存在上一页，则上一页的链接不可单击#}
 {% endif %}
 {# 上一页链接开始#}

 {% for num in appcasesteps.paginator.page_range %}

 {% if num == currentPage %}
 <li class="item active"><a
href="/appcase/appcasestep_manage/?page={{ num }}">{{ num }}</a></li> {#显示当前页数链接#}
 {% else %}
 <li class="item"><a href="/appcase/appcasestep_manage/?page={{ num }}">{{ num }}</a></li>
 {% endif %}
 {% endfor %}

 {# 下一页链接开始#}
 {% if appcasesteps.has_next %} {# 如果有下一页，则正常显示下一页的链接#}
 <li class="next"><a href="/appcase/appcasestep_manage/?page={{ appcasesteps.next_page_number }}">下
一页</a></li>
 {% else %}
 <li class="next disabled"><a href="#">下一页</a></li>
 {% endif %}
 {# 下一页链接结束#}
 </ul>
</div>
</span>
</body>
</html>