Django_f/Django_f/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bug/', include('apps.result.urls')),
    path('api/', include('apps.apitest.urls')),
    path('db/', include('apps.db.urls')),
    path('appcase/', include('apps.apptest.urls')),
    path('webcase/', include('apps.webtest.urls')),
    path('message/', include('apps.message.urls')),
    path('admin/', admin.site.urls),
]

Django_f/apps/apitest/urls.py
from django.urls import path
from apps.apitest import views

app_name = 'apitest'
urlpatterns = [
    path('', views.apimessage, name='api'),
    path ('test_report/', views.test_report, name='report'),
    path('apitest_manage/', views.apitest_manage, name='test'),
    path('apistep_manage/', views.apistep_manage, name='step'),
    path('apisearch/', views.apisearch, name='step'),
    path('welcome/', views.welcome, name='welcome'),

]

Django_f/apps/db/urls.py
from django.urls import path
from apps.db import views

app_name = 'db'
urlpatterns = [
    path('', views.set_manage, name='db_set'),
    path('user/', views.set_user, name='db_user'),

]

Django_f/apps/apitest/models.py
from django.db import models

# Create your models here.
class Apitest(models.Model):
 Product = models.ForeignKey('message.Product',on_delete=models.CASCADE,null=True)
# 关联产品 ID，其中 product 是应用名，Product 是 product 应用的表名
 apitestname = models.CharField('流程接口名称',max_length=64) # 流程接口测试场景
 apitestdesc = models.CharField('描述',max_length=64,null=True) # 流程接口描述
 apitester = models.CharField('测试负责人',max_length=16) # 执行人
 apitestresult = models.BooleanField('测试结果') # 流程接口测试结果
 create_time = models.DateTimeField('创建时间',auto_now=True) # 创建时间，自动获取# 当前时间
 class Meta:
  verbose_name = '流程场景接口'
  verbose_name_plural = '流程场景接口'
 def __str__(self):
  return self.apitestname
class Apistep(models.Model):
 Apitest =models.ForeignKey('Apitest', on_delete=models.CASCADE, ) # 关联接口 ID
 apiname = models.CharField('接口名称',max_length=100) # 接口标题
 apiurl = models.CharField('url 地址',max_length=200) # 地址
 apistep = models.CharField('测试步聚',max_length=100,null=True) # 测试步聚
 apiparamvalue = models.CharField('请求参数和值',max_length=800) # 参数和值
 REQUEST_METHOD = (('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch',
                                                                                            'patch'))
 apimethod = models.CharField(verbose_name='请求方法', choices=
 REQUEST_METHOD, default='get', max_length=200, null=True)  # 请求方法
 apiresult = models.CharField('预期结果', max_length=200)  # 预期结果
 apistep = models.CharField('测试步聚', max_length=100, null=True)  # 测试步聚
 apistatus = models.BooleanField('是否通过')  # 测试结果
 create_time = models.DateTimeField('创建时间', auto_now=True)  # 创建时间，自动获# 取当前时间
 def __str__(self):
    return self.apiname

class Apis(models.Model):
 Product = models.ForeignKey('message.Product',on_delete=models.CASCADE,null=True) # 关联产品ID
 apiname = models.CharField('接口名称',max_length=100) # 接口标题
 apiurl = models.CharField('url 地址',max_length=200) # 地址
 apiparamvalue = models.CharField('请求参数和值',max_length=800) # 请求参数和值
 REQUEST_METHOD = (('0', 'get'),('1', 'post'),('2', 'put'),('3', 'delete'),('4', 'patch'))
 apimethod = models.CharField(verbose_name='请求方法',choices =
 REQUEST_METHOD,default='0',max_length=200) # 请求方法
 apiresult = models.CharField('预期结果',max_length=200) # 预期结果
 apistatus = models.BooleanField('是否通过') # 测试结果
 create_time = models.DateTimeField('创建时间',auto_now=True) # 创建时间，自动获取# 当前时间
 class Meta:
  verbose_name = '单一场景接口'
  verbose_name_plural = '单一场景接口'
 def __str__(self):
  return self.apiname

Django_f/apps/db/models.py
from django.db import models

# Create your models here.
class Set(models.Model):
 setname = models.CharField('系统名称',max_length=64) # 设置名称
 setvalue = models.CharField('系统设置',max_length=200) # 设置值
 class Meta:
  verbose_name = '系统设置'
  verbose_name_plural = '系统设置'
 def __str__(self):
  return self.setname

Django_f/apps/apitest/views.py
from django.shortcuts import render
from apps.apitest.models import Apitest, Apistep, Apis
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import pymysql
# Create your views here.
# @login_required
def apitest_manage(request):
 apitest_list = Apitest.objects.all().order_by('id')  # 获取所有接口测试用例
 username = request.session['username'] # 读取浏览器登录 Session
 paginator = Paginator(apitest_list, 1)  # 生成 paginator 对象，设置每页显示 8 条记录
 page = request.GET.get('page', 1)  # 获取当前的页码数，默认为第 1 页
 currentPage = int(page)  # 把获取的当前页码数转换成整数类型
 try:
  apitest_list = paginator.page(page)  # 获取当前页码数的记录列表
 except PageNotAnInteger:
  apitest_list = paginator.page(1)  # 如果输入的页数不是整数，则显示第 1 页内容
 except EmptyPage:
  apitest_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数# 中，则显示最后一a
 apitest_count = Apitest.objects.all().count() #统计产品数
 return render(request, "resources/apitest.html", {"user": username,"apitests":
apitest_list,"apitestcounts": apitest_count}) #把值赋给 apitestcounts 变量
# 接口步骤管理
# @login_required
def apistep_manage(request):
 username = request.session['username']
 apistep_list = Apistep.objects.all().order_by('id')
 paginator = Paginator(apistep_list, 8)  # 生成 paginator 对象，设置每页显示 8 条记录
 page = request.GET.get('page', 1)  # 获取当前的页码数，默认为第 1 页
 currentPage = int(page)  # 把获取的当前页码数转换成整数类型
 try:
  apistep_list = paginator.page(page)  # 获取当前页码数的记录列表
 except PageNotAnInteger:
  apistep_list = paginator.page(1)  # 如果输入的页数不是整数，则显示第 1 页内容
 except EmptyPage:
  apistep_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中，则显示最后一页内容
 apistep_count = Apistep.objects.all().count()  # 统计产品数
 return render(request, "resources/apistep.html", {"user": username,"apisteps": apistep_list,"apistepcounts": apistep_count})

# @login_required
def apimessage(request):
 username = request.session['username']
 apis_list = Apis.objects.all().order_by('id')
 paginator = Paginator(apis_list, 8)  # 生成 paginator 对象，设置每页显示 8 条记录
 page = request.GET.get('page', 1)  # 获取当前的页码数，默认为第 1 页
 currentPage = int(page)  # 把获取的当前页码数转换成整数类型
 try:
  apis_list = paginator.page(page)  # 获取当前页码数的记录列表
 except PageNotAnInteger:
  apis_list = paginator.page(1)  # 如果输入的页数不是整数，则显示第 1 页内容
 except EmptyPage:
  apis_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中，# 则显示最后一页内容
 apis_count = Apis.objects.all().count()  # 统计产品数
 return render(request, "resources/api.html", {"user": username, "apiss": apis_list, "apiscounts":
   apis_count})  # 把值赋给 apiscounts 变量

# @login_required
def test_report(request):
 username = request.session['username']
 apis_list = Apis.objects.all()
 apis_count = Apis.objects.all().count() #统计接口数
 db = pymysql.connect(user='root', db='django_f', passwd='root', host='127.0.0.1')
 cursor = db.cursor()
 sql1 = 'SELECT count(id) FROM apitest_apis WHERE apitest_apis.apistatus=1'
 aa=cursor.execute(sql1)
 apis_pass_count = [row[0] for row in cursor.fetchmany(aa)][0]
 sql2 = 'SELECT count(id) FROM apitest_apis WHERE apitest_apis.apistatus=0'
 bb=cursor.execute(sql2)
 apis_fail_count = [row[0] for row in cursor.fetchmany(bb)][0]
 db.close()
 return render(request, "report/apitest_report.html", {"user": username,"apiss": apis_list,"apiscounts":
 apis_count,"apis_pass_counts": apis_pass_count,"apis_fail_counts": apis_fail_count}) #把值赋给apiscounts 变量

# 搜索功能
# @login_required
def apisearch(request):
 username = request.session['username'] # 读取浏览器登录 session
 search_apitestname = request.GET.get("apitestname", "")
 apitest_list = Apitest.objects.filter(apitestname__icontains=search_apitestname)
 return render(request,'resources/apitest.html', {"user": username,"apitests":apitest_list})

# 欢迎界面
# @login_required
def welcome(request):
 username = request.session['username']
 return render(request,'logo/welcome.html',{"user": username})

Django_f/apps/db/views.py
from django.shortcuts import render
from apps.db.models import Set
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
# @login_required
def set_manage(request):
 set_list = Set.objects.all().order_by('id')
 username = request.session['username']
 paginator = Paginator(set_list, 8)  # 生成 paginator 对象，设置每页显示 8 条记录
 page = request.GET.get('page', 1)  # 获取当前的页码数，默认为第 1 页
 currentPage = int(page)  # 把获取的当前页码数转换成整数类型
 try:
  set_list = paginator.page(page)  # 获取当前页码数的记录列表
 except PageNotAnInteger:
  set_list = paginator.page(1)  # 如果输入的页数不是整数，则显示第 1 页内容
 except EmptyPage:
  set_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中，
 return render(request, "resources/db.html", {'user':username,"sets": set_list})
# @login_required
def set_user(request):
 user_list = User.objects.all()
 username = request.session['username']
 return render(request, "resources/db_user.html", {'user':username,"users": user_list})

Django_f/templates/resources/apistep.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
<li><a style='color:white' href="/api/apitest_manage/">流程接口测试用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/api/apistep_manage/">流程接口测试步骤</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/api/">单一接口测试用例</a></li>
</ul>
<ul class="nav justify-content-center">
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
<form class="navbar-form" method="get" action="/api/apisearch/">
{% csrf_token %}
<input type="search" name="apitestname" placeholder="名称" required>
<button type="submit">搜索</button>
</form>
</div>
<!-- 流程接口测试步骤-->
<div class="row" style="padding-top: 50px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
<tr>
<th>ID</th><th>接口名称</th><th>接口名称</th><th>参数=值</th><th>方法</th><th>预期结果</th><th>测试结果
</th><th>时间</th><th>业务流名称</th>
</tr>
</thead>
<tbody>
{% for apistep in apisteps %}
<tr>
<td>{{ apistep.id }}</td>
<td>{{ apistep.apiname }}</td>
<td>{{ apistep.apiurl }}</td>
<td>{{ apistep.apiparamvalue }}</td>
<td>{{ apistep.apimethod }}</td>
<td>{{ apistep.apiresult }}</td>
<td>{{ apistep.apistatus }}</td>
<td>{{ apistep.create_time }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div class="container">
 <ul class="pagination" id="pager">
 {# 上一页链接开始#}
 {% if apisteps.has_previous %}
 {# 如果有上一页则正常显示上一页的链接#}
 <li class="previous"><a href="/api/apistep_manage/?page={{ apisteps.previous_page_number }}">上
一页</a></li> {# 上一页标签 #}
 {% else %}
 <li class="previous disabled"><a href="#">上一页</a></li>
     {# 如果当前不存在上一页则上一页的链接不可单击#}
 {% endif %}
 {# 上一页链接开始#}

 {% for num in apisteps.paginator.page_range %}

 {% if num == currentPage %}
 <li class="item active"><a href="/api/apistep_manage/?page={{ num }}">{{ num }}</a></li>
{#显示当前页数链接#}
 {% else %}
 <li class="item"><a href="/api/apistep_manage/?page={{ num }}">{{ num }}</a></li>
 {% endif %}
 {% endfor %}

 {# 下一页链接开始#}
 {% if apisteps.has_next %} {# 如果有下一页，则正常显示下一页的链接#}
 <li class="next"><a href="/api/apistep_manage/?page={{ apisteps.next_page_number }}">下一页
</a></li>
 {% else %}
 <li class="next disabled"><a href="#">下一页</a></li>
 {% endif %}
 {# 下一页链接结束#}
 </ul>
</div>
</span>
<!--统计和翻页功能-->
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:100px; width:100px; ">
<tr><th>总数</th><td>{{ apistepcounts }}</td></tr> {# 前端读取定义的变量#}
</div>
</span>
</body>
</html>

Django_f/templates/resources/apitest.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
<li><a style='color:white' href="/api/apitest_manage/">流程接口测试用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/api/apistep_manage/">流程接口测试步骤</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/api/">单一接口测试用例</a></li>
</ul>
<ul class="nav justify-content-center">
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
<form class="navbar-form" method="get" action="/api/apisearch/">
{% csrf_token %}
<input type="search" name="apitestname" placeholder="名称" required>
<button type="submit">搜索</button>
<!-- 增加 api 流程测试用例-->
<div style="float:right;width:73%">
<select name="Apitest" id="id_Apitest">
<option value="" selected>----api 流程测试用例----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Apitest" data-hreftemplate="/admin/apitest/apitest/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Apitest"
href="/admin/apitest/apitest/add/?_to_field=id&amp;_popup=1" title="增加另一个测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</div>
</form>
</div>
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximumscale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />
<!-- 流程接口列表-->
<div class="row" style="padding-top: 50px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
<tr>
<th>ID</th><th>业务接口流程名称</th><th>执行人</th><th>结果</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for apitest in apitests %}
<tr>
<td>{{ apitest.id }}</td>
<td>{{ apitest.apitestname }}</td>
<td>{{ apitest.apitester }}</td>
<td>{{ apitest.apitestresult }}</td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Apitest"
href="/admin/apitest/apitest/{{ apitest.id }}/change/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Apitest"
href="/admin/apitest/apitest/{{ apitest.id }}/delete/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<div class="container">
<span style="position:absolute; right:100px; bottom:30px;">
 <ul class="pagination" id="pager">
 {# 上一页链接开始#}
 {% if apitests.has_previous %}
 {# 如果有上一页，则正常显示上一页链接#}
 <li class="previous"><a href="/api/apitest_manage/?page={{ apitests.previous_page_number }}">上一页</a></li>
     {# 上一页标签 #}
 {% else %}
 <li class="previous disabled"><a href="#">上一页</a></li>
     {# 如果当前不存在上一页，则上一页的链接不可单击#}
 {% endif %}
 {# 上一页链接结束#}
 {% for num in apitests.paginator.page_range %}
 {% if num == currentPage %}
 <li class="item active"><a href="/api/apitest_manage/?page={{ num }}">{{ num }}</a></li>
     {#显示当页数链接#}
 {% else %}
 <li class="item"><a href="/api/apitest_manage/?page={{ num }}">{{ num }}</a></li>
 {% endif %}
 {% endfor %}
 {# 下一页链接开始#}
 {% if apitests.has_next %} {# 如果有下一页，则正常显示下一页链接#}
 <li class="next"><a href="/api/apitest_manage/?page={{ apitests.next_page_number }}">下一页
</a></li>
 {% else %}
 <li class="next disabled"><a href="#">下一页</a></li>
 {% endif %}
 {# 下一页链接结束#}
 </ul>
 </span>
</div>
<!--统计和翻页功能-->
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:100px; width:100px; ">
<tr><th>总数</th><td>{{ apitestcounts }}</td></tr> {# 前端读取定义的变量#}
</div>
</span>
</body>
</html>

Django_f/templates/resources/db.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
<li><a style='color:white' href="/message/">产品列表</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/db/">设置</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/db/user">系统用户</a></li>
</ul>
<ul class="nav justify-content-center">
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!—设置列表--> <div class="row" style="padding-top: 70px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
    <tr>
<th>ID</th><th>设置名称</th><th>设置的值</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for set in sets %}
<tr>
<td>{{ set.id }}</td>
<td>{{ set.setname }}</td>
<td>{{ set.setvalue }}</td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Set"
href="/admin/db/set/{{ set.id }}/change/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Set"
href="/admin/db/set/{{ set.id }}/delete/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<!--统计和翻页功能-->
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div class="container">
 <ul class="pagination" id="pager">
 {# 上一页链接开始#}
 {% if sets.has_previous %}
 {# 如果有上一页，则正常显示上一页的链接#}
 <li class="previous"><a href="/db/?page={{ sets.previous_page_number }}">上一页
</a></li> {# 上一页标签 #}
 {% else %}
 <li class="previous disabled"><a href="#">上一页</a></li>
     {# 如果当前不存在上一页，则上一页的链接不可单击#}
 {% endif %}
 {# 上一页链接开始#}
 {% for num in sets.paginator.page_range %}
 {% if num == currentPage %}
 <li class="item active"><a href="/db/?page={{ num }}">{{ num }}</a></li>
     {#显示当前页数链接#}
 {% else %}
 <li class="item"><a href="/db/?page={{ num }}">{{ num }}</a></li>
 {% endif %}
 {% endfor %}

 {# 下一页链接开始#}
 {% if sets.has_next %} {# 如果有下一页则正常显示下一页的链接#}
 <li class="next"><a href="/db/?page={{ sets.next_page_number }}">下一页</a></li>
 {% else %}
 <li class="next disabled"><a href="#">下一页</a></li>
 {% endif %}
 {# 下一页链接结束#}
 </ul>
</div>
</span>
</body>
</html>