Django_f/Django_f/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bug/', include('apps.result.urls')),
    path('api/', include('apps.apitest.urls')),
    path('db/', include('apps.db.urls')),
    path('appcase/', include('apps.apptest.urls')),
    path('webcase/', include('apps.webtest.urls')),
    path('message/', include('apps.message.urls')),
    path('admin/', admin.site.urls),
]

Django_f/apps/result/models.py
from django.db import models
from apps.message.models import Product
# Create your models here.


class Bug(models.Model):
 Product = models.ForeignKey('message.Product',on_delete=models.CASCADE, null=True) # 关联产品ID
 bugname = models.CharField('bug 名称',max_length=64) # Bug 名称
 bugdetail = models.CharField('详情',max_length=200)# 详情
 BUG_STATUS = (('激活', '激活'),('已解决', '已解决'),('已关闭', '已关闭'))
 bugstatus = models.CharField(verbose_name='解决状态',choices = BUG_STATUS,default='激活',max_length=200,null=True)# 解决状态
 BUG_LEVEL = (('1', '1'),('2', '2'),('3', '3'))
 buglevel = models.CharField(verbose_name='严重程度',choices =
 BUG_LEVEL,default='3',max_length=200,null=True)# 严重程度
 bugcreater = models.CharField('创建人',max_length=200)# 创建人
 bugassign = models.CharField('分配给',max_length=200)# 分配给
 created_time = models.DateTimeField('创建时间',auto_now=True)# 更新时间值
 class Meta:
  verbose_name = 'bug 管理'
  verbose_name_plural = 'bug 管理'
 def __str__(self):
  return self.bugname

Django_f/templates/logo/HOME.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dhtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
<title>autotestplat-自动化平台测试开发</title>
</head>
 <frameset id="frame1" rows="*" cols="265,*" framespacing="0" frameborder="yes" border="0">
 <frame src="/message/left" name="leftFrame" scrolling="auto" noresize>
 <frame src="/api/welcome" name="mainFrame" scrolling="NO" noresize>
 </frameset>
<noframes>
<body>
</body>
</noframes>
</html>

Django_f/templates/logo/left.html
<html>
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
 <title>autotestplat</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
    <a class="navbar-brand" href="#">&nbsp;</a>
    <ul class="nav justify-content-center">
    <a class="navbar-brand"  style='color:white' href="/api/welcome" target="mainFrame">自动化测试平台</a>
    </ul>
    </div>
    </nav>
<!-- <table border="0">glyphicon glyphicon-credit-card-->
<div class="container-fluid">
<tr> <td>
 <li>
 <a href="../" target="mainFrame" style="font-size:18px">
 <i class="glyphicon glyphicon-gift"></i>
 产品中心
 </a>
 </li>
</tr> </td>

 <tr><td>&nbsp;</td></tr>
 <tr> <td>
 <li>
 <a href="#caseManage" class="nav-header collapsed" data-toggle="collapse"
style="font-size:18px">
 <i class="glyphicon glyphicon-star"></i>
 用例管理
 </a>
 <ul id="caseManage" class="nav nav-list collapse secondmenu" style="height:
0px;">
 <li><a href="/api/apitest_manage"
target="mainFrame">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i
class="glyphicon glyphicon-star"></i>测试用例-api</a></li>
 <li><a href="/appcase/appcase_manage"
target="mainFrame">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i
class="glyphicon glyphicon-star"></i>测试用例-app</a></li>
 <li><a href="/webcase/webcase_manage"
target="mainFrame">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i
class="glyphicon glyphicon-star"></i>测试用例-web</a></li>
 </ul>
 </li>
 </tr> </td>

 <tr><td>&nbsp;</td></tr>
<tr> <td>
 <li>
 <a href="/message/tasks" target="mainFrame" style="font-size:18px">
 <i class="glyphicon glyphicon-fire"></i>
 定时任务
 </a>
 </li>
</tr> </td>

 <tr><td>&nbsp;</td></tr>

<tr> <td>
 <li>
 <a href="/bug/bug_manage" target="mainFrame" style="font-size:18px">
 <i class="glyphicon glyphicon-eye-open"></i>
 bug 管理
 </a>
 </li>
</tr> </td>

 <tr><td>&nbsp;</td></tr>
<tr> <td>
 <li>
 <a href="/api/test_report/" target="mainFrame" style="font-size:18px">
 <i class="glyphicon glyphicon-cog"></i>
 测试报告
 </a>
 </li>
</tr> </td>

 <tr><td>&nbsp;</td></tr>

<tr> <td>
 <li>
 <a href="/db/" target="mainFrame" style="font-size:18px">
 <i class="glyphicon glyphicon-cog"></i>
 系统设置
 </a>
 </li>
</tr> </td>

 <tr><td>&nbsp;</td></tr>

 </div>
 </body>
</html>

Django_f/templates/logo/proc.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
<li><a style='color:white' href="/message/">产品列表</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/db/">设置</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/db/user">系统用户</a></li>
</ul>
<ul class="nav justify-content-center">
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
    <form class="navbar-form" method="get" action="/message/productsearch/">
{% csrf_token %}
<input type="search" name="productname" placeholder="产品名称" required>
<button type="submit">搜索</button>
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximumscale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />
<!-- 增加产品-->
<div style="float:right;width:73%">
<select name="Product" id="id_Product">
<option value="" selected>----产品----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Product" data-hreftemplate="/admin/message/product/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的产品">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Product"
href="/admin/message/product/add/?_to_field=id&amp;_popup=1" title="增加另一个 产品">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</div>
    </form>
<!-- 产品列表-->
<div class="row" style="padding-top: 20px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
<tr><td>&nbsp;</td></tr>
<tr>
<th>ID</th><th>产品名称</th><th>产品描述</th><th>产品负责人</th><th>创建时间</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for product in products %}
<tr>
<td>{{ product.id }}</td>
<td>{{ product.productname }}</td>
<td>{{ product.productdesc }}</td>
<td>{{ product.producter }}</td>
<td>{{ product.create_time }}</td>
<td><a style='color:blue' class="related-widget-wrapper-link add-related" id="add_id_Product"
href="../admin/message/product/{{ product.id }}/change/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Product"
href="../admin/message/product/{{ product.id }}/delete/?_to_field=id&_popup=1"><img
src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div class="container">
 <ul class="pagination" id="pager">
 {# 上一页链接开始#}
 {% if products.has_previous %}
 {# 如果有上一页则正常显示上一页的链接#}
 <li class="previous"><a href="/message/?page={{ products.previous_page_number }}">上
一页</a></li> {# 上一页标签 #}
 {% else %}
 <li class="previous disabled"><a href="#">上一页</a></li>
     {# 如果当前不存在上一页则上一页的链接不可单击#}
 {% endif %}
 {# 上一页链接开始#}

 {% for num in products.paginator.page_range %}

 {% if num == currentPage %}
 <li class="item active"><a href="/message/?page={{ num }}">{{ num }}</a></li>
{#显示当页数链接#}
 {% else %}
 <li class="item"><a href="/message/?page={{ num }}">{{ num }}</a></li>
 {% endif %}
 {% endfor %}

 {# 下一页链接开始#}
 {% if products.has_next %} {# 如果有下一页，则正常显示下一页的链接#}
 <li class="next"><a href="/message/?page={{ products.next_page_number }}">下一页
</a></li>
 {% else %}
 <li class="next disabled"><a href="#">下一页</a></li>
 {% endif %}
 {# 下一页链接结束#}
 </ul>
</div>
</span>
<!--统计和翻页功能-->
<span style="position:absolute; right:100px; bottom:30px;"> {# 把翻页功能固定显示在右下角#}
<div  style="position:absolute; right:100px; width:100px; ">
<tr><th>总数</th><td>{{ productcounts }}</td></tr> {# 前端读取定义的变量#}
</div>
</span>
</body>
</html>

Django_f/templates/logo/sign.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
 <title>AutotestPlat</title>
<style> body{text-align:center} </style>
</head>
<body>
<div>
<font size="1">
<h1>自动化测试平台</h1>
</font>
<form method="post" action="/message/sign/">
{% csrf_token %}
<br>{{ error }}<br>
<br><a>&nbsp;&nbsp;用户名：</a> <input name="username" type="text" placeholder="admin" >
<br><br> <a>&nbsp;&nbsp;密 &nbsp;&nbsp; 码：</a> <input name="password" type="password"
placeholder="admin">
    <br>
    <br>
&nbsp<button style="width:220px;height:28px;" id="submit" type="submit">登 录</button>
</form>
</div>
</body>
</html>

Django_f/templates/logo/welcome.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>autotestplat-自动化平台测试开发</title>
<link href="/static/CSS/bootstrap.min.css" rel="stylesheet">
<style> body{text-align:center} </style>
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
    <li class="nav-link"><a style='color:white' href="/message/logout/" target="_top">退出</a></li>
</ul>
</div>
</nav>
<div class="row" style="padding-top: 100px;">
<div class="container">
<font size="8">
<h1>欢迎您，来到 自动化平台 V1.0</h1>
</font>
</div></div>
<div class="row" style="padding-top: 23px;">
<div class="container">
<tr>
<td><a href="../test_report" target="mainFrame">单击进入测试报告</a></td>
</tr>
</div></div>
</body>
</html>